### ISSUE TITLE
Typo in blog

### ISSUE THREAD

**Issue by boyobejamin** [pfertyk/blog#5]
On this page `https://pfertyk.me/2023/02/creating-aws-lambda-functions-with-terraform/`

The section `Installing modules locally` needs to be updated as follows to ensure the dependencies layer is picked up at runtime.

Per AWS Docs, either the cache path or local path `./python` is read for module imports. Since the Terraform zip provider has some opinionations around zip'ing files, we need to create a folder in `./layers/python` for dependencies so that the path `./python` exists when the deps layer is extracted

```
  # https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-dependencies-layers
  # Verify your zip contains the directories expected per the docs
  provisioner "local-exec" {
    command = "mkdir -p ${path.module}/layer/python && python3 -m pip install -r requirements.txt -t ${path.module}/layer/python"
  }
```

**Comment by pfertyk** [comment]
Hi! Sorry for the delay, and thanks for reporting this ;) I received another piece of feedback recently about the S3 website example not working, and it turned out that another AWS resource needs to be added to Terraform ... so it's quite possible that the Lambda example is also no longer working as well ;) I will take a look at this soon and update the code if necessary :)

**Comment by pfertyk** [comment]
I've checked my Lambda and API Gateway templates and indeed, they no longer work. I've updated both of them, as well as the blog post about AWS Lambda:

https://github.com/pfertyk/blog/commit/0244402a90090e42b1fa9f5123317aeac626a0cc
https://github.com/pfertyk/terraform-templates/commit/38f961fc30f165ed12377019b1ee0aac5d152ff8

Thank you again for reporting this! :)
